version: "3.8"
services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        container_name: PHP_Server
        volumes:
            - ./server:/var/www/html/